uvmf:
  environments:
    add_env:
      agents:
      - initiator_responder: INITIATOR
        name: agent_in
        type: in_intf
      - initiator_responder: INITIATOR
        name: agent_out
        type: out_intf
      analysis_components:
      - name: add_pred
        parameters: []
        type: add_predictor
      analysis_exports:
      - connected_to: add_pred.agent_out_ae
        name: add_pred_ep
        trans_type: out_intf_transaction
      analysis_ports:
      - connected_to: agent_in.monitored_ap
        name: agent_in_ap
        trans_type: in_intf_transaction
      - connected_to: agent_out.monitored_ap
        name: agent_out_ap
        trans_type: out_intf_transaction
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: add_sb
        sb_type: uvmf_in_order_race_scoreboard
        trans_type: out_intf_transaction
      subenvs: []
      tlm_connections:
      - driver: agent_in.monitored_ap
        receiver: add_pred.agent_in_ae
        validate: 'True'
      - driver: agent_out.monitored_ap
        receiver: add_sb.actual_analysis_export
        validate: 'True'
      - driver: add_pred.add_sbo_ap
        receiver: add_sb.expected_analysis_export
        validate: 'True'
